# name: Continuous Integration - Unit Tests and End-to-End Tests

# on:
#   pull_request:
#     branches:
#       - main

# jobs:
#   test:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: 14

#       - name: Install dependencies
#         run: npm install

#       - name: Run unit tests
#         run: npm test

#       - name: Run end-to-end tests
#         uses: cypress-io/github-action@v6
#         with:
#             config-file: cypress.config.js

# name: Cypress Tests

# on:
#   pull_request:
#     branches:
#       - main

# jobs:
#   cypress-run:
#     runs-on: ubuntu-22.04
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#       # Install NPM dependencies, cache them correctly
#       # and run all Cypress tests
#       - name: Cypress run
#         uses: cypress-io/github-action@v6
#         with:
#           start: npm start

name: example-basic
# This workflow represents a set of basic End-to-End tests
on:
  pull_request:
    branches:
      - main

jobs:

  basic-ubuntu-20:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress tests
        uses: cypress-io/github-action@v6